# Generated by Django 6.0.4 on 2026-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='truck_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
